# Generated by Django 2.2.7 on 2020-09-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0004_timetable_class_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='class_table_list',
            field=models.TextField(null=True),
        ),
    ]
