# Generated by Django 2.2.7 on 2020-09-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0005_timetable_class_table_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='steps',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sweeps',
            field=models.IntegerField(default=1000),
        ),
    ]
