# Generated by Django 2.2.7 on 2020-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0006_auto_20200916_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='sweeps',
        ),
        migrations.AddField(
            model_name='timetable',
            name='reads',
            field=models.IntegerField(default=1000),
        ),
    ]
