# Generated by Django 2.2.7 on 2020-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0007_auto_20200916_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='reads',
            field=models.IntegerField(default=10),
        ),
    ]
