# Generated by Django 2.2.7 on 2020-09-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0008_auto_20200916_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='convenience',
            field=models.TextField(default='{}'),
        ),
    ]
