# Generated by Django 2.2.7 on 2020-10-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0010_timetable_lunch_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='class_table_list_for_display',
            field=models.TextField(null=True),
        ),
    ]
