# Generated by Django 2.2.7 on 2020-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0013_timetable_koma_data_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='class_dict',
            field=models.TextField(null=True),
        ),
    ]
