# Generated by Django 2.2.7 on 2020-10-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0015_remove_timetable_class_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='teacher_table_list',
            field=models.TextField(null=True),
        ),
    ]
