# Generated by Django 2.2.7 on 2020-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0016_timetable_teacher_table_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='jugyo_list',
            field=models.TextField(null=True),
        ),
    ]
