# Generated by Django 2.2.7 on 2020-10-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0018_auto_20201024_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='renzoku_ID',
            field=models.TextField(default='[]'),
        ),
    ]
