# Generated by Django 2.2.7 on 2020-10-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0019_timetable_renzoku_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='con4_display',
            field=models.TextField(default='{}'),
        ),
    ]
