# Generated by Django 2.2.7 on 2020-10-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0020_timetable_con4_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='gen_dict',
            field=models.TextField(default='{}'),
        ),
    ]
