# Generated by Django 2.2.7 on 2020-11-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0023_auto_20201123_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fix_display',
            field=models.TextField(default='[]'),
        ),
    ]
